// DO NOT EDIT!
// Code generated by gdbinder <https://github.com/Jun-Chang/gdbinder>

package example

import (
	"database/sql"
)

func TestStruct2Clmns() string {
	return "id,col1,col2,col3,col4,col5,col6,col7,col8,col9,col10"
}

func TestStruct2Scan(rs sql.Rows) ([]*TestStruct2, error) {
	bound := []*TestStruct2{}
	for rs.Next() {
		b := TestStruct2{}
		if err := rs.Scan(&b.ID, &b.Col1, &b.Col2, &b.Col3, &b.Col4, &b.Col5, &b.Col6, &b.Col7, &b.Col8, &b.Col9, &b.Col10); err != nil {
			return nil, err
		}
		bound = append(bound, &b)
	}

	return nil, bound
}
