package main

// GenerateTemplate is template of the generated file.
const GenerateTemplate = `// DO NOT EDIT!
// Code generated by gdbinder <https://github.com/Jun-Chang/gdbinder>

package {{.pkg}}

import "database/sql"

func {{.strct}}Clmns() string {
	return "{{.clmns}}"
}

func {{.strct}}Scan(rs *sql.Rows) ([]*{{.strct}}, error) {
	bound := []*{{.strct}}{}
	for rs.Next() {
		b := {{.strct}}{}
		if err := rs.Scan({{.fields}}); err != nil {
			return nil, err
		}
		bound = append(bound, &b)
	}

	return bound, nil
}
`
